# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "MEA Book: Python Tutorial for Analyzing MEA Recording"
author: Takuma Furukawa
logo: icon.png
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/tk-neuron/meabook # Online location of your book
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "icon.png"
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false
  baseurl: "https://tk-neuron.github.io/meabook/"
  announcement: "MEA Bookは執筆途中です."

exclude_patterns:
  - venv/*

launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://mybinder.org" # The URL for your BinderHub (e.g., https://mybinder.org)

sphinx:
  extra_extensions:
    - sphinxext.opengraph
  config:
    html_extra_path: ["datasets"]
    ogp_site_url: "https://tk-neuron.github.io/meabook/"
    ogp_image: "https://tk-neuron.github.io/meabook/_static/icon.png"
    ogp_description_length: 200

launch_buttons:
  notebook_interface        : "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  colab_url                 : "https://colab.research.google.com" # The URL of Google Colab (https://colab.research.google.com)
